server.port=8083
spring.application.name=restaurant-service

# Database Configuration (Port 3306 for XAMPP default)
spring.datasource.url=jdbc:mysql://localhost:3306/tetouan_tourism_restaurant?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.tetouan.tourism=DEBUG
